import {
  Home,
  MessageCircle,
  Sparkles,
  Code2,
  Compass,
  Bot,
  Boxes,
  Plug,
  Briefcase,
  Users,
  GraduationCap,
  Bell,
  User as UserIcon,
  Settings as SettingsIcon,
  Shield,
  type LucideIcon,
} from "lucide-react";

export type SubPage = {
  slug: string; // "" means the module index
  label: string;
  description: string;
};

export type ModuleDef = {
  key: string;
  label: string;
  path: string;
  icon: LucideIcon;
  description: string;
  pages: SubPage[];
};

export const MODULES: ModuleDef[] = [
  {
    key: "home",
    label: "Home",
    path: "/home",
    icon: Home,
    description: "Your TriniAI dashboard.",
    pages: [
      { slug: "", label: "Dashboard", description: "Recent activity, usage, shortcuts, and recommendations." },
      { slug: "recent", label: "Recent Chats", description: "Quick access to previous conversations." },
      { slug: "actions", label: "Quick Actions", description: "One-click buttons for Chat, Image, Code, and Research." },
      { slug: "suggestions", label: "AI Suggestions", description: "Recommended prompts and ideas." },
    ],
  },
  {
    key: "chat",
    label: "Chat",
    path: "/chat",
    icon: MessageCircle,
    description: "Talk with Trinity 1.0.",
    pages: [
      { slug: "", label: "New Chat", description: "Start a new conversation." },
      { slug: "history", label: "Chat History", description: "View previous chats." },
      { slug: "pinned", label: "Pinned Chats", description: "Important conversations." },
      { slug: "shared", label: "Shared Chats", description: "Chats shared with others." },
      { slug: "search", label: "Search Chats", description: "Search through conversations." },
      { slug: "voice", label: "Voice Chat", description: "Speech-based interaction." },
    ],
  },
  {
    key: "imagine",
    label: "Imagine",
    path: "/imagine",
    icon: Sparkles,
    description: "Generate images, video, music, voice, and 3D.",
    pages: [
      { slug: "", label: "Image Generator", description: "Text to image." },
      { slug: "image-editor", label: "Image Editor", description: "Modify images." },
      { slug: "image-history", label: "Image History", description: "Generated images." },
      { slug: "video", label: "Video Generator", description: "Text to video." },
      { slug: "video-history", label: "Video History", description: "Saved videos." },
      { slug: "music", label: "Music Generator", description: "Create songs." },
      { slug: "voice", label: "Voice Generator", description: "Generate speech." },
      { slug: "voice-clone", label: "Voice Cloning", description: "Custom voices." },
      { slug: "three-d", label: "Text to 3D", description: "Generate 3D models." },
      { slug: "three-d-history", label: "3D History", description: "Previous models." },
    ],
  },
  {
    key: "code",
    label: "Code",
    path: "/code",
    icon: Code2,
    description: "Build software with AI.",
    pages: [
      { slug: "", label: "Projects", description: "Programming projects." },
      { slug: "files", label: "File Manager", description: "Project files." },
      { slug: "editor", label: "Editor", description: "Code editor." },
      { slug: "assistant", label: "AI Assistant", description: "Coding AI." },
      { slug: "terminal", label: "Terminal", description: "Execute commands." },
      { slug: "preview", label: "Live Preview", description: "View applications." },
      { slug: "github", label: "GitHub", description: "Repository management." },
    ],
  },
  {
    key: "explore",
    label: "Explore",
    path: "/explore",
    icon: Compass,
    description: "Research the web and your documents.",
    pages: [
      { slug: "", label: "Search", description: "Internet search." },
      { slug: "research", label: "Deep Research", description: "Advanced analysis." },
      { slug: "pdf", label: "PDF Reader", description: "Read documents." },
      { slug: "web", label: "Web Pages", description: "Website summaries." },
      { slug: "youtube", label: "YouTube Search", description: "Video research." },
      { slug: "flashcards", label: "Flashcards", description: "Study cards." },
      { slug: "quiz", label: "Quiz Generator", description: "Generate quizzes." },
      { slug: "mindmaps", label: "Mind Maps", description: "Visual learning." },
    ],
  },
  {
    key: "agents",
    label: "Agents",
    path: "/agents",
    icon: Bot,
    description: "Trinity Router and specialist agents.",
    pages: [
      { slug: "", label: "Trinity Agent", description: "Main orchestrator." },
      { slug: "research", label: "Research Agent", description: "Research specialist." },
      { slug: "coding", label: "Coding Agent", description: "Programming specialist." },
      { slug: "image", label: "Image Agent", description: "Image generation." },
      { slug: "video", label: "Video Agent", description: "Video creation." },
      { slug: "audio", label: "Audio Agent", description: "Voice and music." },
      { slug: "browser", label: "Browser Agent", description: "Web interaction." },
      { slug: "planner", label: "Planner Agent", description: "Task planning." },
      { slug: "memory", label: "Memory Agent", description: "Long-term memory." },
      { slug: "judge", label: "Judge Agent", description: "Evaluates responses." },
    ],
  },
  {
    key: "models",
    label: "Models",
    path: "/models",
    icon: Boxes,
    description: "Cloud and local AI models.",
    pages: [
      { slug: "", label: "Installed Models", description: "Active models." },
      { slug: "architecture", label: "Trinity Architecture", description: "How Trinity routes every task." },
      { slug: "cloud", label: "Cloud Models", description: "Online models." },
      { slug: "download", label: "Download Models", description: "Marketplace downloads." },
      { slug: "upload", label: "Upload Models", description: "Import custom models." },
      { slug: "ollama", label: "Ollama Models", description: "Local models." },
      { slug: "marketplace", label: "Model Marketplace", description: "Discover models." },
    ],

  },
  {
    key: "mcp",
    label: "MCP Hub",
    path: "/mcphub",
    icon: Plug,
    description: "Connect tools via Model Context Protocol.",
    pages: [
      { slug: "", label: "Installed MCPs", description: "Connected tools." },
      { slug: "canva", label: "Canva MCP", description: "Design integration." },
      { slug: "github", label: "GitHub MCP", description: "Code integration." },
      { slug: "figma", label: "Figma MCP", description: "UI/UX integration." },
      { slug: "drive", label: "Google Drive MCP", description: "Storage integration." },
      { slug: "search", label: "Search MCP", description: "Search engine." },
      { slug: "research", label: "Deep Research MCP", description: "Multi-source analysis." },
      { slug: "browser", label: "Browser MCP", description: "Website automation." },
    ],
  },
  {
    key: "workspace",
    label: "Workspace",
    path: "/workspace",
    icon: Briefcase,
    description: "Your notes, files, and projects.",
    pages: [
      { slug: "", label: "Notes", description: "Personal notes." },
      { slug: "files", label: "Files", description: "File management." },
      { slug: "documents", label: "Documents", description: "Document storage." },
      { slug: "tasks", label: "Tasks", description: "Task manager." },
      { slug: "calendar", label: "Calendar", description: "Scheduling." },
      { slug: "projects", label: "Projects", description: "Workspace projects." },
    ],
  },
  {
    key: "community",
    label: "Community",
    path: "/community",
    icon: Users,
    description: "Collaborate with others.",
    pages: [
      { slug: "", label: "Teams", description: "Group collaboration." },
      { slug: "projects", label: "Shared Projects", description: "Team projects." },
      { slug: "templates", label: "Templates", description: "Reusable templates." },
      { slug: "leaderboard", label: "Leaderboard", description: "Rankings and achievements." },
    ],
  },
  {
    key: "learn",
    label: "Learn",
    path: "/learn",
    icon: GraduationCap,
    description: "Personal AI tutoring and study tools.",
    pages: [
      { slug: "", label: "AI Tutor", description: "Personal teacher." },
      { slug: "tutor", label: "ET Tutor", description: "Lesson → quiz → revision plan." },
      { slug: "study", label: "Study Assistant", description: "Study support." },
      { slug: "exam", label: "Exam Mode", description: "Exam preparation." },
      { slug: "career", label: "Career Roadmap", description: "Future planning." },
    ],
  },
  {
    key: "notifications",
    label: "Notifications",
    path: "/notifications",
    icon: Bell,
    description: "System updates and alerts.",
    pages: [{ slug: "", label: "Notifications", description: "System updates." }],
  },
  {
    key: "profile",
    label: "Profile",
    path: "/profile",
    icon: UserIcon,
    description: "Your account.",
    pages: [
      { slug: "", label: "Account", description: "User information." },
      { slug: "stats", label: "Statistics", description: "Usage analytics." },
      { slug: "subscription", label: "Subscription", description: "Plans and limits." },
      { slug: "security", label: "Security", description: "Password and sessions." },
    ],
  },
  {
    key: "settings",
    label: "Settings",
    path: "/settings",
    icon: SettingsIcon,
    description: "Configure TriniAI.",
    pages: [
      { slug: "", label: "General", description: "Basic settings." },
      { slug: "appearance", label: "Appearance", description: "Dark/light theme." },
      { slug: "ai", label: "AI Settings", description: "Model preferences." },
      { slug: "voice", label: "Voice Settings", description: "Voice configuration." },
      { slug: "memory", label: "Memory Settings", description: "Memory controls." },
      { slug: "privacy", label: "Privacy", description: "Storage permissions." },
      { slug: "notifications", label: "Notifications", description: "Alerts." },
      { slug: "language", label: "Language", description: "Localization." },
      { slug: "integrations", label: "Integrations", description: "External services." },
      { slug: "backup", label: "Backup", description: "Export and restore." },
    ],
  },
  {
    key: "admin",
    label: "Admin",
    path: "/admin",
    icon: Shield,
    description: "Administration and moderation.",
    pages: [
      { slug: "", label: "Dashboard", description: "Analytics overview." },
      { slug: "architecture", label: "Backend Architecture", description: "Stack, schema, sync, and fallback." },
      { slug: "users", label: "Users", description: "Manage accounts." },

      { slug: "logs", label: "Chat Logs", description: "Moderation." },
      { slug: "models", label: "Models", description: "Enable/disable models." },
      { slug: "mcp", label: "MCP Hub", description: "Manage integrations." },
      { slug: "keys", label: "API Keys", description: "Provider keys." },
      { slug: "analytics", label: "Analytics", description: "Usage charts." },
      { slug: "moderation", label: "Moderation", description: "Warnings and bans." },
      { slug: "broadcast", label: "Broadcast Center", description: "Send announcements." },
      { slug: "prompts", label: "Prompt Library", description: "System prompts." },
      { slug: "security", label: "Security Logs", description: "Monitor activity." },
      { slug: "backup", label: "Backup & Restore", description: "System recovery." },
      { slug: "health", label: "System Health", description: "Server status." },
      { slug: "limits", label: "Limits & Roles", description: "Permissions." },
      { slug: "training", label: "Training Dataset", description: "Trinity learning data." },
    ],
  },
];

export function findModule(key: string): ModuleDef | undefined {
  return MODULES.find((m) => m.key === key);
}
